package: api
output: ../api/petstore-server.gen.go
additional-imports:
  - package: github.com/Peyton232/HTTPServerGenerator/exampleServer/models
    alias: .
generate:
  echo-server: true
  embedded-spec: true